### ISSUE TITLE
sticky title

### ISSUE THREAD

**Issue by ah-bas-und-aer** [GuidaGG/vielfaeltig#27]
- This works good in desktop now! Superduper guys!
- The font size is not always fitting the logo – I suggest we rather use the type logo as usual type. What do you think?
<img width="810" alt="Bildschirmfoto 2024-02-05 um 22 33 35" src="https://github.com/GuidaGG/vielfaeltig/assets/124358378/5e94e203-935f-4d32-a3ec-4a91b0e77eed">
- For mobile the position is a little bit to low. 
- For the extra pages it is frustrating to not have directly the title next to the logo, isn't it?. Can we have the title directly next to the title?
Datenschutzerklärung = title „Sicher“ (Datenschutzerklärung needs to be wirtten in headline 1 below), Jobs = title „Jobs", Kontaktformular: title = fragen
**or**
for all additional pages (besides the main) the text-logo is gone and only the gender star stays next to the sticky title
This also will avoid the strange look of Datenschutz on mobile (check also XD: https://xd.adobe.com/view/770b8a67-668a-40e0-93f5-65f260cbb802-2258/)

**Comment by GuidaGG** [comment]
we need the logo without text in svg. Currrently I only find it in png.

**Comment by GuidaGG** [comment]
- For mobile the position is a little bit to low. - For the extra pages it is frustrating to not have directly the title next to the logo, isn't it?. Can we have the title directly next to the title? Datenschutzerklärung = title „Sicher“ (Datenschutzerklärung needs to be wirtten in headline 1 below), Jobs = title „Jobs", Kontaktformular: title = fragen **or** for all additional pages (besides the main) the text-logo is gone and only the gender star stays next to the sticky title This also will avoid the strange look of Datenschutz on mobile (check also XD: https://xd.adobe.com/view/770b8a67-668a-40e0-93f5-65f260cbb802-2258/)

-yes but then on pages that are not the homepage it wont be possible to use the normal "sticky headers". I will just make it htat the default title of the page is fixed ot the top.
Is this an ok compromise? otherwise I have to change the whole tempaltes because of the paddings.

**Comment by GuidaGG** [comment]
![image](https://github.com/GuidaGG/vielfaeltig/assets/9657908/c8a8ef3c-7355-49b3-bc65-1a892f8f4392)

Will look like this

**Comment by ah-bas-und-aer** [comment]
This sounds good. sicher shuld be written in small letters though :) And „Datenschutzerklärung“ needs to be written before Päambel. But I can do that.

**Comment by GuidaGG** [comment]
- [ ] add svg to backedn
- [ ] add title in header next to logo
- [ ] hide title on mobile
- [ ] create special "fixed" class for fixed main titles
