### ISSUE TITLE
From the meeting yesterday

### ISSUE THREAD

**Issue by ah-bas-und-aer** [GuidaGG/vielfaeltig#39]
- The category “über uns“ should be called "wir"
- instead of the quote in the beginning they want to have the claim (I changed it already), if we delete the text line on top of the adress, what does it mean to you?
- instead the paragraph will be placed below the title "wir", i already placed it there 
- mobile: sometimes and not all the time the titels still where displaced. I think it is just a loading issue?

**Comment by GuidaGG** [comment]
- instead of the quote in the beginning they want to have the claim (I changed it already), if we delete the text line on top of the adress, what does it mean to you?
Thsi is just coming from backend, so It wont affect the code.

-The category “über uns“ should be called "wir"
this is also backend

- mobile: sometimes and not all the time the titels still where displaced. I think it is just a loading issue?
  - my phone is not working so I cant properly work on mobile at the moment.

**Comment by GuidaGG** [comment]
I will close this since it is mostly content questions and the mobile has its own issues.
