### ISSUE TITLE
upload, 08.02.

### ISSUE THREAD

**Issue by ah-bas-und-aer** [GuidaGG/vielfaeltig#41]
- general: Akkordeon spacing strange
- general: in the contact form the outline of the text fiel "Telefonnummer" is missing
- geneal: irregular button styling in akkordeon (one plus has the round background, the accordeon lernen and beraten (konditionen) is missing
- general: the akkoredeon titles are breaking in a strange why, also I set up the plugin adjustments
- general: do we still not need a cookie warning pop up? 
- general: ankerpoint for "wir" on mobile and desktop check.
- gerneal: can you change the status comment like that: Stand: "02.2024, vielfältig. GmbH", i cannot find it myself 
- mobile: is it only on my phone, that the sticky title is very close to the logo? there could be a tiny bit more spacing

**Comment by GuidaGG** [comment]
- general: Akkordeon spacing strange
  - done. I think this was when I try to add more spacing between the sections. Please use the spacer element for this. 
- general: in the contact form the outline of the text fiel "Telefonnummer" is missing
  - done
- geneal: irregular button styling in akkordeon (one plus has the round background, the accordeon lernen and beraten (konditionen) is missing
  -   I removed what I tried to make the buttons inside still have background.
- general: the akkoredeon titles are breaking in a strange why, also I set up the plugin adjustments
  -  I still kept <a> elements as breaking anywhere because there are some huge linsk tha break the layout but for the collapsible we dont need anymore that you set up the typography.
- gerneal: can you change the status comment like that: Stand: "02.2024, vielfältig. GmbH", i cannot find it myself 
  - done

comments:
- general: ankerpoint for "wir" on mobile and desktop check.
  - you will have to give more space netween title and quote, i think. Im afraid if I change paddings now it will create other problems in the placements of the sticky
- general: do we still not need a cookie warning pop up? 
   -  They need, because of the formular. THere should be plugins for htis.
- mobile: is it only on my phone, that the sticky title is very close to the logo? there could be a tiny bit more spacing

**Comment by GuidaGG** [comment]
I think they might not need a cookie banner, but for sure they need some part in thedatenschutz erklarung about what they do with the information people send in the forms and information about what to do if the visitor wants then to delete all data.
