### ISSUE TITLE
Footer Logo implementation

### ISSUE THREAD

**Issue by ah-bas-und-aer** [GuidaGG/vielfaeltig#46]
- Implementation of more than one row of logos should be possible
- Align all to the horizontal center of the row
- Can they automatically turned into this uni-color white?

todo:
- [x] add custom post  - footer logos to backend
- [x] display from custom post
- [x] add style
- [x] implement changes and readd content

**Comment by GuidaGG** [comment]
Olá,
the partners section is still accessible via the costumizer. you can add as much partners as you want.
since the logos were all a bit diferent I added two options on the backend:
- for logos that are not a transparent png you can check the box "multiply"
- for colored logos you will probbaly need to check the box "invert", to make the logo white instead of black/darkgrey"

**Comment by GuidaGG** [comment]
Uh, and I added a new plugin : Kirki Customizer Framework in order to have this "repeater" field in the customizer.

**Comment by ah-bas-und-aer** [comment]
oh I love this solution! This is really handy! 
The plugin creates this button „add new row“?
