### ISSUE TITLE
(AH) change layout order

### ISSUE THREAD

**Issue by ah-bas-und-aer** [GuidaGG/vielfaeltig#54]
@GuidaGG 
on the staging page I shifted the contakt info down. Can you explain me how to direct the page correctly to the beginning of a chapter? 
If I am in the area of "kontakt" now and want to change to "angebote" it is not going up totally.

**Comment by GuidaGG** [comment]
![image](https://github.com/GuidaGG/vielfaeltig/assets/9657908/c5d03262-39c0-4429-b237-825255721a30)

You need to give the corresponding ID to the div/p/a in the content where you want the anchor to scroll to.
In this case, the ID "angebote" is added to the paragraph (i just added this btw because it was not working)

and this you do here: HTML-anchor

![image](https://github.com/GuidaGG/vielfaeltig/assets/9657908/194b314c-4022-43bb-bb08-9f6665ed90e3)

**Comment by ah-bas-und-aer** [comment]
@GuidaGG I know how to add an anchor, what I am struggeling with is the position. F.i. if you scroll down and go back to ankorpoint “angebote“ the sticky title is right at its place, but not the content below. Same with "kontakt“. There needs to be an adjustment of position. You can tell me where, so I might know next time.
